### ISSUE TITLE
Erreur : 1

### ISSUE THREAD

**Issue by Lcharp99** [mdefrance/AutoCarver#1]
**_The following error occured :_**

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Continuum\Miniconda3\envs\py37\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

~\AppData\Local\Continuum\Miniconda3\envs\py37\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

~\AppData\Local\Continuum\Miniconda3\envs\py37\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 1

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18512\4215378455.py in <module>
      1 ds = prepare_db('../../DATA/')
      2 ds_nodt = ds[["is_fraud", "flag_financement", "flag_impaye_30", "mt_archive_24m", "mt_archive", "anciennete_lcl", "last_chiffre_affaires", "chiffre_affaires_0", "mean_delai_reglement_6m", "tranche_effectif_entreprise", "last_note_irpro", "mt_facture", "mt_impaye_bdf_nt_6m", "nb_impaye", "last_note_luc", "nb_impaye_en_cours"]]
----> 3 carv = carving(ds)

~\Desktop\git\data_monitoring_ghd\data_monitoring\CODE\streamlit\utils_st.py in carving(ds)
     68     auto_carver = AutoCarver(values_orders, sort_by='cramerv', max_n_mod=5, copy=True, keep_nans=True, verbose=False)
     69 
---> 70     X_train_process = auto_carver.fit_transform(X_train_process, y_train, X_test=X_train_process, y_test=y_train)
     71 
     72     # Final pipeline for carving the dataset

~\AppData\Local\Continuum\Miniconda3\envs\py37\lib\site-packages\sklearn\base.py in fit_transform(self, X, y, **fit_params)
    853         else:
    854             # fit method of arity 2 (supervised transformation)
--> 855             return self.fit(X, y, **fit_params).transform(X)
    856 
    857 

~\AppData\Local\Continuum\Miniconda3\envs\py37\lib\site-packages\AutoCarver\AutoCarver.py in fit(self, X, y, X_test, y_test)
    127 
    128             # getting best combination
--> 129             best_groups = self.get_best_combination(feature, X, y, X_test, y_test)
    130 
    131             # feature can not be carved robustly

~\AppData\Local\Continuum\Miniconda3\envs\py37\lib\site-packages\AutoCarver\AutoCarver.py in get_best_combination(self, feature, X, y, X_test, y_test)
    157         # measuring association with target for each combination and testing for stability on TEST
    158         best_groups = best_combination(combinations, self.sort_by, xtab[notna(xtab.index)], 
--> 159                                        xtab_test[notna(xtab_test.index)])
    160 
    161         # update of the values_orders grouped modalities in values_orders

~\AppData\Local\Continuum\Miniconda3\envs\py37\lib\site-packages\AutoCarver\AutoCarver.py in best_combination(combinations, sort_by, xtab, xtab_test)
    332 
    333         # same target rate order in TRAIN and TEST
--> 334         train_target_rate = combi_xtab[1].divide(combi_xtab[0]).sort_values()
    335         test_target_rate = combi_xtab_test[1].divide(combi_xtab_test[0]).sort_values()
    336         viability = viability and all(train_target_rate.index == test_target_rate.index)

~\AppData\Local\Continuum\Miniconda3\envs\py37\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3456             if self.columns.nlevels > 1:
   3457                 return self._getitem_multilevel(key)
-> 3458             indexer = self.columns.get_loc(key)
   3459             if is_integer(indexer):
   3460                 indexer = [indexer]

~\AppData\Local\Continuum\Miniconda3\envs\py37\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 1

It's probably about train_target_rate (combi_xtab[1]) but I can't say. I think it can't reach the second element of combi_xtab.

**Comment by ZacharieBuisson1** [comment]
I think there is an issue with one of your feature. You may check if some of your features is full of nan, or has only value. It might solve your issue.

HAve a nice day, respectfully.

**Comment by mdefrance** [comment]
Hi,

Thanks for your report @Lcharp99 and thanks for your response @ZacharieBuisson1.

This error has been handled in version 4.0.0, data types are now checked before any transformation: https://github.com/mdefrance/AutoCarver/blob/4d4b8e220d6348c607b028951d534aa5e897fa34/AutoCarver/AutoCarver.py#L116
