### ISSUE TITLE
problem with FeatureSelector: best_features does not return the good list of variables

### ISSUE THREAD

**Issue by JoseAngelGarciaSanchez** [mdefrance/AutoCarver#2]

**Comment by mdefrance** [comment]
Hello, thanks for the issue. Any precision about what exactly goes wrong?
Regarding the 'best_features' attribute of FeatureSelector, it will be ordered according to the association measure in the next package update. Will that solve your issue?

**Comment by mdefrance** [comment]
Hello @JoseAngelGarciaSanchez. I have further information about your issue. The comportment your describing is expected. As misleading as it might seem, the selected ``best_features`` are not only those displayed in the output. Indeed, features are selected according to all of the provided measures (set in the ``measures`` attribute). Per measure, a ranking of features is defined, and a set of ``best_features`` is selected for each measure. The output of the ``Featureselector`` is the concatenation of all of those sets of selected features. This comportment might change in a feature update. Hope that clarified things!
