### ISSUE TITLE
Issue with feature selection - unbelievable behavior

### ISSUE THREAD

**Issue by ZacharieBuisson1** [mdefrance/AutoCarver#3]
Hello Mario DEFRANCE ! 

At a time when the issue of AutoCarver is increasingly debated, there is growing concern over feature selection. 

Indeed, for a given sample of features to evaluate, if no one pass filters, code go wrong with the following error. 

**KeyError: "None of ['feature'] are in the columns"**

Please let me know if you need help to solve this issue. Otherwise, thanks for considering my request.

Regards, Zacharie.

**Comment by mdefrance** [comment]
Hello dear @ZacharieBuisson1. I have some good news for you. This issue should de be patched in v5.1.2, out now! Feel free to come back to me for any other issue! 
Mario
