### ISSUE TITLE
[Discretizer] Unexpected value! Missing values found for feature 'feature_name' at transform step but not during fit.

### ISSUE THREAD

**Issue by anquev** [mdefrance/AutoCarver#69]
Hello @mdefrance 

I am facing this issue with the Carver because one of my variables did not contain NaNs for the `fit_transform`, but the same variable contains NaNs in the dev set. Since my carver does not seem to handle this condition, I can't apply the `transform` to the dev set unless I manually replace the NaNs with a modality from the carver. Is `update_discretizer()` the solution to my problem ?

Thanks for your consideration, 
Antoine

**Comment by mdefrance** [comment]
Hello @anquev 

Thanks for your issue.

The behavior you're referring to is to be expected. 

- Let's say you have a feature X which takes modalities from x1 to x9 on your train set. For each of those values Carvers learn a target rate/mean. Modalities x1 to x9 are grouped according to those learned values. 

- Let's say now that, on new data (in your dev set), your feature X starts taking values y1 to y9.  Your trained Carver does not know their associated target rates/means and, thus, is enable to group them with previously seen modalities.

- Same applies to missing values

In the end, your options are the following:
 - (not recommended) do not use a dev set in Carvers -> risk to overfit on your data, and experience poorer performance on new data
 - (recommended) take a bigger sample as your dev set -> which better represent the extent of all possible values taken by your data, make sure there are missing values in both train and dev
 - Furthermore, as you mentioned, you could use `update_discretizer()`, make sure to follow this [example](https://autocarver.readthedocs.io/en/latest/examples/Carvers/ContinuousRegression/continuous_regression_example.html#Updating/Adjusting-AutoCarver)

Hope that helps!
